services:
  postgres:
    image: postgres:16-alpine3.19
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=naruto
      - POSTGRES_DB=contacts
